### ISSUE TITLE
GNSS and iridium modem at the same time

### ISSUE THREAD

**Issue by eried** [sparkfunX/Artemis_Global_Tracker#1]
If I cannot have both on without damaging the board (?):

Is it ok to be constantly switching them (i.e. every 5 minutes check the position) just to be always connected to receive Ring alerts? Has anyone tried this? (do Ring alerts actually repeat? so it is not that crucial to be offline for a while?)

**Comment by PaulZC** [comment]
Hi Erwin (@eried),
You cannot have both GNSS and Iridium on at the same time as the antenna switch could be damaged. Iridium uses 5V and GNSS uses 3.3V. They could be connected through the antenna switch. Please do not try to enable both at the same time.
You will receive two ring alerts from Iridium, a few seconds apart, when there is a new message to be downloaded. But only two. They do not repeat again.
Please see Example11 for more details.
https://github.com/sparkfunX/Artemis_Global_Tracker/tree/master/Software/examples
I am closing this issue. If you need more help or suggestions, please ask in the SparkX Forum:
https://forum.sparkfun.com/viewforum.php?f=123
Best wishes,
Paul
