### ISSUE TITLE
adding external 3-wires sensor

### ISSUE THREAD

**Issue by jerabaul29** [sparkfunX/Artemis_Global_Tracker#13]
I want to add a 3-wire sensor in this kind: https://www.sparkfun.com/products/11050

Do you think it will be ok to interface it on the board pins D35 and / or D4? These are not used for anything else, right?

Btw, this is the only thing that is a bit sad: not having access to more of the MCU pins. Guess there is no way with the present board to access more pins, right? If there is a v2 some time, would be great with having more pins available for doing other stuff :) .

**Comment by PaulZC** [comment]
Hi JR,

One of the design requirements for the AGT was to keep it as small and as light as possible. It is a very compact, congested PCB. Squeezing in extra Input/Output breakouts would be difficult...

Yes, you can use D35 or D4 to interface to that sensor. They are not used for anything else. If you are not using the SPI pins, then you can use those for I/O or one-wire too. They are D5, D6, D7:
![image](https://user-images.githubusercontent.com/5690545/104422398-a05dc800-5574-11eb-8eb5-a2282bc4dd4f.png)

If you need more I/O, there are I2C or SPI "port expanders" available:
https://www.sparkfun.com/products/17047

Best wishes,
Paul
