### ISSUE TITLE
Read binary messages

### ISSUE THREAD

**Issue by a-schneider-fmi** [sparkfunX/Artemis_Global_Tracker#25]
Your Python tools do not support binary SBD messages yet. I have implemented Python functions to translate binary SBD messages. Are you interested in taking over the code to your repository? If so, I can make a pull request.

**Comment by PaulZC** [comment]
Hi @a-schneider-fmi ,
I guess you are referring to the mapping tools? (The AGT configuration tool does support both text and binary messaging.)
Sure, please submit a PR and I will gladly take a look at it.
Many thanks,
Paul

**Comment by a-schneider-fmi** [comment]
Hi Paul,
Yes, I refer to the mapping tools. I have written a simple script that queries emails via IMAP, translates each binary message to a dictionary, and creates a GPX file from all messages via the gpxpy library. Plain command line script, no GUI. Yet I suppose the modularized functionality to parse binary messages is interesting to other users. I'll prepare a pull request.
Andreas

**Comment by a-schneider-fmi** [comment]
Shall I convert my script to a plain message translator to avoid duplicating the email download functionality? Although it is not really a duplicate since I use IMAP instead of the GMail API, which can be used with a wider range of providers.
