### ISSUE TITLE
additional pins on "v1.2"

### ISSUE THREAD

**Issue by jerabaul29** [sparkfunX/Artemis_Global_Tracker#41]
Hi @PaulZC ,

Sorry for "insisting" a bit on this, but we have a real pain problem with getting enough pins available for putting some weather measurement sensors, wind anemometers, etc, on some of our designs. We could of course add an Artemis Nano over I2C to have more pins, but this is more costs, yet a board to put in our design, more programming to do etc.

I was wondering: any hope that you could set up a "v1.2" rather than a v2, that would just be the present v1, but with more pins broken out? Looking at my board, I wonder if there would be any more space for breaking pins (for example, 1 more under the VBus pins, a bunch of them in place of where the "SparkX" mention is the the top side of the board, a couple "North East" from the GPS chip, a bunch at the "North" of the board close to the supercaps. Getting between 5 to 10 extra pins would make a huge difference for us :) .

**Comment by PaulZC** [comment]
Hi JR,
Request noted! Thank you for asking nicely. My colleague has managed to squeeze in 8 extra pins around the NW corner (4 West, 4 North), plus one more below VBUS. The design is still being reviewed, we will share the new pin numbers and positions as soon as we can.
Have a great weekend,
Paul

**Comment by jerabaul29** [comment]
Yippiii, this is excellent news, many thanks for taking our feedback into account :) . 9 extra pins sounds amazing (you know how users are, "the more the better" :) ).

@jvoermans FYI, this should solve the issues you had, right? :) .

Hope the testing is successful and the next production runs has the extra pins :) . Many thanks again, will be eager to hear about how this goes further and when the boards with extra pins hit the market :) .

**Comment by jerabaul29** [comment]
A last point I was thinking about: which pins did you decide to route? Can you provide at least one or two of the "power switch pins" (maybe one high side and one low side?) mentioned in the datasheet "Absolute Maximum Rating"? That would be very convenient to be able to switch on / off some "intermediate" loads, and cut the need for extra switches / transistors / breakouts such as the qwiic switch.

**Comment by jerabaul29** [comment]
(for reference: https://cdn.sparkfun.com/assets/d/e/8/b/4/Apollo3_Blue_MCU_Data_Sheet_v0_12_1_rZ9Akgo.pdf#G24.7640541 ).

**Comment by lewispg228** [comment]
Hi @jerabaul29 ,
I have been working on the revision to this design. Thanks for all your input on this!

It was pretty tight, but I was able to nudge some stuff and breakout at least one low-side power switch pin (D37) right below VBUS. The other 8 GPIO broken out in the NW corner are the following: AD32, D43, D42, AD31, AD29, AD11, D15, AD12.

Thanks again for your feedback!
Pete

**Comment by jerabaul29** [comment]
Many thanks, that sounds excellent, it will make a huge improvement for us :) .

Then looking forward to these boards on the SF online shop :) . Feel free to close this issue, all sounds good to me :) .

**Comment by jerabaul29** [comment]
PS: I am ordering a bunch of AGTs together with a colleague, and we got to hear that there are AGTs in production or soon to be. Will these be v1.2 (would be amazing :) ), or v1.1?

**Comment by lewispg228** [comment]
Hi @jerabaul29 ,
The current AGT boards are being built in SparkX, and so they are the version, "X10". (this is what I believe you are referring to as "v1.1". 

The newer version, that will include the changes discussed here, will be "v10". And they will be red colored PCBs. You can always check the bottom copper for the version number.

Sorry if our versioning system may seem confusing :) Everything from SparkX starts with an "X", and then if/when the product transitions to a SparkFun product (Red PCBs), then the versions start with a "v", and it usually starts with "v10" as it is the first version built by SparkFun.

We have "v10" red PCBs on order, and we are cranking on all the other stuff involved (test jigs/documentation/arduino-libraries/ERP-work/purchasing-parts). Sorry I can't give you a firm date, but I assure you it will be going live ASAP :)

Again, thanks for all your feedback - and ORDERS!

Cheers,
Pete

**Comment by jerabaul29** [comment]
That sounds amazing :) No worries at all, this is very clear, makes a lot of sense, and we are looking forward to it :) .

A small tips: really hope that you produce a large chunk of these. As you maybe know, we already have 8 in backorders. We also got 2 "small fundings" in addition, one for around 15kUSD, one for around 20kUSD, and we will use these all for building AGT-based sea ice drifters - so you can do the math, about half the funding goes to buying AGTs, the other half goes to the components around, batteries, etc :) . We hope for some larger fundings for next year.

**Comment by jerabaul29** [comment]
PS: I will build a "master PCB" to host the AGTv10, and make it easy to add the components I use, such as the 9dof I use (this one, if you start producing a clone would be amazing: https://www.adafruit.com/product/4569 so that I do not need to order for plenty of different suppliers), pololu step up step down converter 3.3V (same, annoying to order from different sources, having something like https://www.pololu.com/product/2122 it would be amazing), Qwiic Switch, and some extra stuff. If you are able to release a CAD file (ideally KiCAD, that's what we like best :) ) for the AGTv10 so that I can use it as a "shield fingerprint" even if it is before it gets available on the webshop, would be amazing, because then I can order my "master PCBs" asap so that I can start testing as soon as the AGTv10s get available :) .

**Comment by lewispg228** [comment]
Hey @jerabaul29 ,
Perhaps this would be a suitable SparkFun option for your 3.3V buck/boost:

https://www.sparkfun.com/products/15208

I know it's a little bit larger, but it is pretty comparable in terms of specs.

Also, maybe one of our 9DOF offerings would work for you. Is there a specific spec/range/rate that you really need from the ISM330DHCX + LIS3MDL combo?

https://www.sparkfun.com/products/15335
https://www.sparkfun.com/products/13284
https://www.sparkfun.com/products/13944

Hope this helps,
Cheers,
Pete

**Comment by jerabaul29** [comment]
Hi @lewispg228 ,

Many thanks for your message :) .

A few thoughts:

- I am actually quite dependent on the slightly larger power input range of the pololu (works from 2.7V). It is crazy how much temperatures of -40C can impact batteries, and I am pretty sure that voltage goes down to 2.8-2.9V with the batteries I use at the peak of Iridium transmission. Also, it is actually quite nice to have a fixed 3.3V output when building series of 20 or so instruments, as this avoids the risks of mishaps / mis configuration of buttons etc,  just one less thing that can go wrong... So I think for now I will stick to https://www.pololu.com/product/2122 'unfortunately', but if SF comes with a similar or better design with fixed 3.3V out and input from around 2.7 to 12V, I will happily change to SF for simplifying my supply chain :) .
- similarly for the 9dof, I really want to avoid 'all in 1 IMU solutions', I had far too much headaches with the BNO08x to give these one more chance. About the ICM, some colleagues at another Institute were unfortunately not too impressed with the noise level either. Regarding the 9dof you show, unfortunately these have no built in temperature compensation. This is, together with lower noise, the killer features of the ISM330DHCX + LIS3MDL that I need. For example the ISM330DHCX + LIS3MDL has noise density of 60 to 100 ug/sqrt(Hz), Vs not specified in the datasheet of the LSMDS1. Adafruit did some noise comparisons on the gyros, and the LSMDS1 had about 4 time more noise than the ISM330DHCX https://learn.adafruit.com/adafruit-sensorlab-gyroscope-calibration/comparing-gyroscopes . All in all, the ISM330DHCX is a quite different level of performance. I do need this full level of performance in my application. So if you produce something similar I would go for it rather than Adafruit - simpler sourcing for me - , if you can find some even better performance 9dof that is a nice bonus (I could go to 30 or 40 USD without too much pain I think :) ), but I need something at least as good, if not better, than the ISM330DHCX, and with temperature compensation built it :) .

If you start producing / selling this kind of breakouts some day that would be awesome :) .

**Comment by lewispg228** [comment]
Hey @jerabaul29 ,
Thanks for this info! We will definitely look more into the ISM330DHCX + LIS3MDL combo.

I did a little more digging about the buck/boost, and (although I'm not 100% sure yet, without testing) it looks like our board can actually do 2V-16V on the input. We used the TPS63070, and the datasheet clearly states 2-16V. I'm not sure why our documentation shows only 3-16V. It may have been to "play it safe", but I will look into this more next week and do some testing. What kind of current do you usually pull for your system?

Also, for reference, the Pololu board is using a similar model of the IC; it uses the TPS63060, which in it's datasheet, shows 2.5-12V. So that makes sense why they might advertise 2.7V to 11.8V.

https://www.ti.com/lit/ds/symlink/tps63070.pdf
https://www.ti.com/lit/ds/symlink/tps63060.pdf

**Comment by jerabaul29** [comment]
Ok, many thanks for the infos :) . Let me know how the tests go :) .

**Comment by jerabaul29** [comment]
PS: max 0.75 Amp, likely 0.5 Amp.

**Comment by jerabaul29** [comment]
Many thanks for the addition of the extra pins on the new, "red" AGT :) . Closing.
