### ISSUE TITLE
Default measurement values should be outside the physically valid range

### ISSUE THREAD

**Issue by a-schneider-fmi** [sparkfunX/Artemis_Global_Tracker#42]
The default values of the measured quantities (like pressure, temperature, humidity, latitude, longitude, altitude) basically act as a fill value if the measurement has failed and thus should be outside the range of a valid measurement. That way an invalid measurement can immediately be distinguished from a real one. For example, if the GPS measurement fails the message currently contains the position 0°N, 0°E, 0m which is a valid position, but using, e.g., INT32_MIN would indicate an invalid position. Similarly, UINT16_MAX can signal an invalid humidity and INT16_MAX an invalid temperature.

**Comment by PaulZC** [comment]
Hi Andreas,
I agree! If you'd like to submit a pull request, I will happily merge it.
Best wishes,
Paul
