### ISSUE TITLE
Link to the repo of the new AGT "red" and mention that this is deprecated?

### ISSUE THREAD

**Issue by jerabaul29** [sparkfunX/Artemis_Global_Tracker#44]
Would it be possible to i) explain that this was the "prototype" AGT, and that it has been replaced by the "AGT gone red", and ii) link to the repo of the new AGT "red" at https://github.com/sparkfun/SparkFun_Artemis_Global_Tracker , and maybe mark this repo as outdated or something like this? :) . That would be very convenient for avoiding that people get confused :) .

**Comment by PaulZC** [comment]
Hi JR,

OK. Done.

To quote Douglas Adams: "So long and thanks for all the fish"!

All the best,
Paul
