### ISSUE TITLE
specs: max transient intensity

### ISSUE THREAD

**Issue by jerabaul29** [sparkfunX/Artemis_Global_Tracker#7]
One more power supply question: what is the max transient intensity use in Amps that the batteries should be able to supply? :)

**Comment by PaulZC** [comment]
It will be somewhere between 300mA and 400mA, depending on the supercapacitor charge current, but you would need to measure it to be sure.

**Comment by jerabaul29** [comment]
Thanks! As this is important for choosing the batteries, I wonder if this issue should be sticky and / or the information added to the documentation :) .

**Comment by PaulZC** [comment]
Thanks JR (@jerabaul29) - good suggestion. Added here:
https://github.com/sparkfunX/Artemis_Global_Tracker/tree/master/Documentation/GlobalTracker_FAQs
